Tweets = new Mongo.Collection('tweets'); // use a mongoDB to store stuff...
Profile = new Mongo.Collection('profile'); // use a mongoDB to store stuff...
Scraped = new Mongo.Collection('scraped');
UnfollowDB = new Mongo.Collection('unfollowdb');
TimeDB = new Mongo.Collection('TimeDB'); 
Counts = new Mongo.Collection('Counts');